sudo: false
language: node_js
node_js:
- stable
- lts/*
- 8
matrix:
  fast_finish: true
  allow_failures:
  - node_js: stable
cache: yarn
script:
- yarn build
- yarn lint
- yarn $CMD
after_success:
- '[ "CMD" == master ] && npm run coverage'
notifications:
  email: false
