sudo: false
language: node_js
node_js:
- stable
- lts/*
matrix:
  fast_finish: true
  allow_failures:
  - node_js: stable
cache: yarn
env:
  matrix:
  - CMD=test
  - CMD=lint
script:
- npm run $CMD
after_success:
- '[ "CMD" == master ] && npm run coverage'
notifications:
  email: false
  slack:
    secure: M1j+k19RrYEz0rdcyhfU4547/OGCUvobYygr90DYA0y2bo4nAhPd3v27xnfc6gvOYwCVHLg7jaO6qBjE1qsrb3FsxThs+PPdKsfLGWsvoZj7MlFRfUAfuzZqB3Bh/vK+By5OTcL9Q1STrPCbn+ue52xJPyTO5Ay3tUuV94Ilim6js9v7skBmtqRGUaW/OjZU1CaG5milbYgZH+Zx9ERC4thqBpQ3ZuJhZtJeVdZbaAhc9C8JuyFTkQEb9zxM9gbBtcquttJ+K18H3KbeaazDV9Hv6uzGOeSl9Lnkp4KmcS5BcotjBLYh06ZjlD5fV6oZ3YlbEqCF4vogI6lOz0SlicdAnNw/wOCooEmiiP+fegRNJDQOiskjoh+NFFnAV66ScPi+/X8ilRBGLEpZS8vp/Jnua8zxETyIh5GJ4ZHLfiGXbE+glyCCeeWz2ZF4xzKlmDsoYZwGUtGrHbeko+Hivv7MDVdMLg3bKtQcvC5KMBQJKvH1gA9WFjSWdT4eXW755tM9OZeT5sW2c0Smz9bsitUgvUEwPJFed38VWlI9IlHYed+u3x28oZkXkTJ3YigPj9lg61UAt+l5dOFv7G/2TrFfAraUQwgCanZKFb/1UK+IUnkw06xAIqMLdE51qOL9mtDmDQuh5QN60cYxeSxM13txEdCM6Vd8S7w18jKn278=
