sudo: false
language: node_js
node_js:
- stable
- lts/*
- 8
matrix:
  fast_finish: true
  allow_failures:
  - node_js: stable
cache: yarn
script:
- npm run build
- npm run lint
- npm test
after_success:
- npm run coverage
notifications:
  email: false
